version: "3.7"


x-restart-policy: &restart_policy
  restart: unless-stopped

services:
  bot:
    << : *restart_policy
    image: ghcr.io/knownblackhat/links-server-discord-bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    tty: true

    environment:
      - TOKEN=BotTokenHere
