name: Bot Runner

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Run Container
      run: |
        docker run -i  -e TOKEN=${{ secrets.token }} ghcr.io/knownblackhat/links-server-discord-bot:latest
