name: Bot Runner

on: [workflow_dispatch]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Run Container
      run: |
        docker run -i ghcr.io/mr-robot-discord-bot/mr-robot:latest -e TOKEN=${{ secrets.token }}
