name: Bot Runner

on: [workflow_dispatch]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependency
      run: |
        pip install -r requirements.txt
        apt install ffmpeg -y

    - name: Run Bot
      run: TOKEN=${{ secrets.token  }} python bot.py
