name: Bot Runner

on: [workflow_dispatch]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache APT packages
      uses: actions/cache@v2
      with:
        path: ~/.apt/cache
        key: ${{ runner.os }}-apt
        restore-keys: |
          ${{ runner.os }}-apt

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Dependency
      run: |
        sudo apt update -y
        sudo apt install ffmpeg -y
        pip install -r requirements.txt

    - name: Run Bot
      run: TOKEN=${{ secrets.token }} python bot.py
